config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  patch 'switch-view/:view_style' => 'home#switch_view', as: :switch_view

  devise_for :users

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# Adding resources for Items Controller
  resources :items do
  	member do
    patch :complete
  	patch :uncomplete
  end
end

# Add route path for Items controller
	root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
  belongs_to :assignee, class_name: 'User', optional: true

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ApplicationRecord

	# Createa associations for user and items
	has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def switch_view
    session[:view_style] = params[:view_style]
    redirect_back fallback_location: root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy, :complete, :uncomplete]

	def index
		if user_signed_in?
			@items = Item.where(:user_id => current_user.id).or(Item.where(assignee_id: current_user.id)).order("created_at DESC")
			@users = User.all

			respond_to do |format|
				format.html { render :index }
				format.json { render json: @items.to_json}
			end
		end
	end

	def new
		@item = current_user.items.build
	end

	def show

	end

	def edit
	end

	def update
		if @item.update(item_params)
			respond_to do |format|
				format.html { redirect_to items_path }
				format.js { render js: "alert('updated')" }
			end
		else
			respond_to do |format|
				format.html { render 'edit' }
				format.js { render js: "alert('Not updated')" }
			end
		end
	end

	def create
		@item = current_user.items.build(item_params)
		#@username = user.find(session[:current_user.id]).name
		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path
	end

	def complete
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path
	end

	def uncomplete
		@item.update_attribute(:completed_at, nil)
		redirect_to root_path
	end

	private

	def item_params
		params.require(:item).permit(:title, :description, :assignee_id)
	end

	def find_item
		@item = Item.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, label: "Item" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Todo-List Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<% if user_signed_in? %>
	<div class="col-md-8 col-md-offset-4">

	<% @items.each do |item| %>

	<% if item.completed? %>

	<div class="row item">

		<div class="col-md-6">
			<h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
			<% if session[:view_style] && session[:view_style] == 'title-with-details' %>
				<p style="opacity: 0.5;" class="item-desc item-sub-title"><%= item.description %></p>
				<p style="opacity: 0.5;" class="time-ago item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago </p>
			<% end %>
		</div>

		<div class="col-md-4">
			<%= form_for item, remote: true, authenticity_token: true do |f| %>
				<%= f.select :assignee_id, options_for_select(@users.map {|u| [u.email, u.id]}, item.assignee.try(:id)), { include_blank: 'Assign to a user' }, class: 'form-control', disabled: true %>
			<% end %>
		</div>

		<div class="col-md-1">
			<p><%= link_to uncomplete_item_path(item), method: :patch do %></p>
				<i class="fa fa-lg fa-check"></i>
			<% end %>
		</div>


		<div class="col-md-1">
			<p><%= link_to item, method: :delete, data: {Confirm: "Are you sure, you want to delete the task?" } do %></p>
				<i class="fa fa-lg fa-trash"></i>
			<% end %>
		</div>

	</div>
	<% else %>

	<div class="row item">
		<div class="col-md-6">
			<h2 class="item-title"><%= link_to item.title, item %></h2>
			<% if session[:view_style] && session[:view_style] == 'title-with-details' %>
				<p class="item-desc item-sub-title"><%= item.description %></p>
				<p class="time-ago item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago </p>
			<% end %>
		</div>

		<div class="col-md-4">
			<%= form_for item, remote: true, authenticity_token: true do |f| %>
				<%= f.select :assignee_id, options_for_select(@users.map {|u| [u.email, u.id]}, item.assignee.try(:id)), { include_blank: 'Assign to a user' }, class: 'form-control  assignee-select' %>
			<% end %>
		</div>


		<div class="col-md-1">
			<p><%= link_to complete_item_path(item), method: :patch do %></p>
				<i class="fa fa-lg fa-check"></i>
			<% end %>
		</div>


		<div class="col-md-1">
	<p><%= link_to item, method: :delete, data: {Confirm: "Are you sure, you want to delete the task?" } do %></p>
		<i class="fa fa-lg fa-trash"></i>
			<% end %>
		</div>
	</div>

	<% end %>
<% end %>

	</div>

<% else %>
<%= render 'layouts/static_landing_page' %>
<% end %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<h1>Create Task!</h1>
	<%= render 'form' %>

</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">

		<h2><%= @item.title %></h2>
		<p><%= @item.description %></p>

		<%= link_to "Back", root_path, class: "btn btn-primary" %>
    <% unless @item.completed? %>
  		<%= link_to "Edit", edit_item_path(@item), class: "btn btn-primary" %>
    <% end %>

</div>

app/views/layouts/_static_landing_page.html.erb
<div class="jumbotron col-md-10 col-md-offset-2">
	<h1>Tada! Check your Todo List!</h1>
	<p>Track your work.</p>
	<%= link_to "Register", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-default">
    <div class="container col-md-9 col-md-offset-2">
      <div class="navbar-header ">
    <%= link_to "Todo List", root_path, class: "navbar-brand" %>
  </div>

  <ul class="nav navbar-nav">
    <li><%= link_to "Register", new_user_registration_path %></li>
    <% if current_user.present? %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

      <% else %>

      <li><%= link_to "Login", new_user_session_path %></li>

    <% end %>
  </ul>

  <% if user_signed_in? %>
    <%= link_to "New Task", new_item_path, class: "navbar-text navbar-link navbar-right" %>

    <div class="btn-group navbar-right" role="group" aria-label="...">
      <%= link_to '', switch_view_path('title'), method: :patch, class: "btn btn-default glyphicon glyphicon-menu-hamburger #{ 'active' if session[:view_style] == 'title'}", title: 'Title-only view' %>
      <%= link_to '', switch_view_path('title-with-details'), method: :patch, class: "btn btn-default glyphicon glyphicon-th-list #{ 'active' if session[:view_style] == 'title-with-details'}", title: 'Title-and-details view' %>
    </div>
  <% end %>
  </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>